[project]
name = "movie-sentiment-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cookiecutter>=2.7.1",
    "dagshub>=0.7.2",
    "mlflow>=3.16.1",
    "nltk>=3.10.3",
    "scipy>=1.15.3",
    "setuptools>=84.0.0",
    "xgboost>=3.2.0",
]
