[project]
name = "movie-sentiment-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "awscli>=1.46.1",
    "cookiecutter>=2.7.1",
    "dagshub>=0.7.2",
    "dvc[s3]>=3.67.1",
    "flask>=3.1.3",
    "mlflow>=3.16.1",
    "nltk>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "prometheus-client>=0.26.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "setuptools>=84.0.0",
    "xgboost>=3.2.0",
]
